version: '3.9'

services:
  rabbit:
    container_name: rabbit
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    ports:
      - "15672:15672"

  client:
    container_name: client
    image: client:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ./client/data
        target: /data
      - type: bind
        source: ./client/config.ini
        target: /config.ini
    depends_on:
      - loader
    restart: on-failure

  loader:
    container_name: loader
    image: loader:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Loader
      - PORT=8888
    ports:
      - "8888:8888"
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure


  trips_consumer1:
    container_name: trips_consumer1
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Trips_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  trips_consumer2:
    container_name: trips_consumer2
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Trips_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  trips_consumer3:
    container_name: trips_consumer3
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Trips_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  trips_consumer4:
    container_name: trips_consumer4
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Trips_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  trips_consumer5:
    container_name: trips_consumer5
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Trips_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  stations_consumer1:
    container_name: stations_consumer1
    image: stations_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Stations_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure

  weather_consumer1:
    container_name: weather_consumer1
    image: weather_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - APP_ENTRYPOINT=Weather_Consumer
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure
