version: '3.9'

services:

  client:
    container_name: client
    image: client:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - type: bind
        source: ./client/data
        target: /data
      - type: bind
        source: ./client/config.ini
        target: /config.ini
    # depends_on:
    #  - loader
    restart: on-failure

  loader:
    container_name: loader
    image: loader:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    # depends_on:
    #  - rabbit
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    restart: on-failure
